### ISSUE TITLE
remove svg from the plot display options

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRdisplay#13]
svg is simply not ready to be used for bigger plots :-(

This plot makes scrolling while the plot is visible a pain. Igraph also [has some problems with it's svg based plotting](https://github.com/igraph/python-igraph/issues/36#issuecomment-118855778). IMO it should be removed in irkernel (following the way it is done by the ipython kernel) or demoted in the notebook behind the bitmap based graphic formats.

``` r
library(magrittr)
library(ggplot2)
#options(jupyter.plot_mimetypes = c("text/plain", "image/png" )) # no more svg...
opt = theme(legend.position  = "none",
panel.background = element_rect(fill="violetred4"),
axis.ticks       = element_blank(),
panel.grid       = element_blank(),
axis.title       = element_blank(),
axis.text        = element_blank())
seq(from=-10, to=10, by = 0.05) %>%
expand.grid(x=., y=.) %>%
ggplot(aes(x=x, y=y)) +
geom_point(alpha=.1, shape=20, size=1, color="white", stroke=0) + opt
```

**Comment by flying-sheep** [comment]
just add `options(jupyter.plot_mimetypes = c('text/plain', 'image/png'))` before the plotting if you have too big data.

i’d say it’s an user error: if there’s so many elements that browsing gets slow, you can’t interpret them anyway and should have used smoothScatter:

![](http://i.stack.imgur.com/ntfa9.png)

**Comment by jankatins** [comment]
That might be, but to correct that you have to scroll to the cell again, which is annoying...

IMO we should not have defaults which annoy users. 

These plots are not interactive so a user anyway can't zoom in which is IMO the only reason why svg would be better. And if a user wants to have svg, they are free to use the option...

**Comment by jankatins** [comment]
Another problem is that I can't even save the svg as there is no "save image" when I right click on the svg (probably because the iframe :-().

**Comment by jankatins** [comment]
And another problem with SVG: https://github.com/IRkernel/IRkernel/issues/291#issuecomment-208045684

In that case, a 53MB SVG file is created and the browser doesn't like it.

Can we please remove SVG until browsers catch up?

**Comment by jankatins** [comment]
So, IMO I have a strong case for removing svg from the default plot options:
- it can't be right-click saved
- it now-and-then produces a data stream which crashes the browser or makes it slow as hell

The only reason for SVG is crisper text.

The first to reasons make for a bad user experience and I think we should have defaults which work all the time out of the box.

I've added the 0.4 milestone, as I think this should be decided before the next release...

**Comment by takluyver** [comment]
I'm leaning towards removing svg. @flying-sheep , do you want to make a case for keeping it?

**Comment by flying-sheep** [comment]
yes, multiple times: it exposes bugs in the underlying technologies.

that ggplot thing is probably the 5th or 6th time that we found a bug somewhere due to it.

the non-rightclickability is due to the standalone flag. an alternative would be to use a `data:image/svg+xml;base64,...`

---

i can see the problems of course: obviously this strategy is good for the ecosystem (because nobody would configure it to SVGs manually, so no more bugs will surface) but less good for the users (because they encounter more bugs and annoyances).

there’s two obvious alternatives – remove SVG from the defaults or keep it – and two compromises we can think about:
1. what about including a size threshold? we emit a `message` when the output is too big and therefore likely trips browsers, and return `NULL`. users aren’t annoyed (it’s just a small message, not a browser-breaking thing), but it’s still visible and will be reported.
2. if you really want to remove SVG by default, we should do retina PNGs by default (double DPI, same size in inches, manually supply width/height in metadata). going back to blurryness stuff isn’t the way to go.

**Comment by takluyver** [comment]
Exposing bugs is all well and good, but I'm not convinced that it's worth the pain. We're making an interactive programming environment, not a browser SVG testing tool ;-).

I quite like the size threshold idea, though. Can we tell that quickly from the R side? Could it be terribly slow generating the SVG even if we don't send it to the browser?

**Comment by flying-sheep** [comment]
> We're making an interactive programming environment, not a browser SVG testing tool

yes, you’re right. but i think we’re married to Jupyter so the jupyter bugs we exposed are almost ours. ggplot not so much, but that finding is still nice!

> Can we tell that quickly from the R side?

well, surely after the fact: create the SVG and simply check its `length()`.

> Could it be terribly slow generating the SVG even if we don't send it to the browser?

yes, @janschulz said in https://github.com/IRkernel/IRkernel/issues/291#issuecomment-208045684 that it takes ages. then again that’s a ggplot bug. i don’t think we should compromise to work around other people’s bugs.

the only valid reason to change/remove SVG display is IMHO proper, well-constructed plots that are too big because they have far too many points: they might might take shorly to generate and still make browsers lag, and i don’t think browsers can easily “fix” this.

**Comment by flying-sheep** [comment]
so we have to check
1. are browsers still slow if we put “big” SVGs in `<img>`? if not, we have to make Jupyter do that. (this is a valid assumption because browsers don’t need to maintain the DOM tree in `<img>`s all the time, and “big” SVGs aren’t really big before the lagging starts)
2. are lag-inducingly big SVGs fast to create? then we can introduce the size threshold

**Comment by takluyver** [comment]
> i don’t think we should compromise to work around other people’s bugs.

We can't have an inflexible rule here. Does the project you think is responsible agree that it's a bug? What are the chances of it getting fixed in the near future? If it's uncertain, sometimes we have to compromise on things like this. There's a fine line between solving problems and finger pointing, and the open source community is weaker when it strays into the latter.

> well, surely after the fact: create the SVG and simply check its length().

I also wonder if we can check the length of the recordedplot object - I suspect that may be strongly correlated with the size of the svg produced, and if so, we can skip generating the svg entirely.

**Comment by flying-sheep** [comment]
> There's a fine line between solving problems and finger pointing, and the open source community is weaker when it strays into the latter.

that wasn’t my intention. rather “they’ll be happy we found a barely-visible bug for them”

but you’re right: this project’s goal is more pragmatic than i am :wink: 

> I also wonder if we can check the length of the recordedplot object - I suspect that may be strongly correlated with the size of the svg produced, and if so, we can skip generating the svg entirely.

very good point, didn’t think of that!

we can create one for @janschulz’ bad ggplot object and inspect it.

PS: we could also add specialized ggplot reprs. one one hand for the [text representation](https://blog.ouseful.info/2016/04/29/first-thoughts-on-automatically-generating-accessible-text-descriptions-of-ggplot-charts-in-r/) ~~on the other hand because `ggsave` probably creates better output than following an indirection through R’s graphics devices.~~ /edit: [nope](https://github.com/hadley/ggplot2/blob/master/R/save.r)

**Comment by takluyver** [comment]
> that wasn’t my intention. rather “they’ll be happy we found a barely-visible bug for them”

Did we file an issue on ggplot? It's fine to claim it's a bug elsewhere, so long as we're working on getting it fixed

> /edit: nope

It's not immediately obvious to me from that code - is ggsave just doing the same plot-replay thing that repr does?

**Comment by jankatins** [comment]
> yes, @janschulz said in IRkernel/IRkernel#291 (comment) that it takes ages. then again that’s a ggplot bug. i don’t think we should compromise to work around other people’s bugs.

One could also argue that it is not a bug but a special case: I don't really know is specifying data directly in the `aes()` call is supported or should be done by specifying a new data.frame  -> lets see what the ggplot maintainer tell us in hadley/ggplot2#1626...

Anyway: there will always be situations where the dataframe is too big and the user attempts plotting anyway. And then "interactive work" becomes staring at the screen for a minute without a way to abort as AFAIK "interrupt" does not interrupt at all during plotting thanks to the r kernel beeing single threaded and restart leaves behind the old r kernel as the current "killer" does not work with the way the r kernel is actually in a child process.

And plotting it twice as much time until the plot shows up at the user.

**Comment by jankatins** [comment]
Actually I think that it would be nice if something like "option for the kernel" would be part of the messaging protocol. Then nbconvert could use that to configure the default plot type to use pdf for pdf output and in the notebook could use a user configured value...

**Comment by flying-sheep** [comment]
we already do this in IRkernel, so i’m closing this. the option set in here, `jupyter.display_mimetypes`, explicitly has _all_ mimetypes

**Comment by jankatins** [comment]
I didn't mean the option but something which would be set _once_ in the UI and then communicated to all kernels. 

Anyway: I still stand by my opinion that it's not nice to use users as guinea pigs or as a kind of "find the bugs/problems in other packages"-service as it is not good for the reputation (vs RStudio) or the IRkernel and jupyter notebook in the R world. But I don't think we will agree on this and you are responsible for the packages.

**Comment by flying-sheep** [comment]
whoops, i thought we already changed it in the kernel [here](https://github.com/IRkernel/IRkernel/blob/master/R/options.r)

apparently we didn’t. i accepted the change [here](https://github.com/IRkernel/IRdisplay/issues/13#issuecomment-217633958), although probably not 100% clear:

> this project’s goal is more pragmatic than i am
