### ISSUE TITLE
clarification license and “creator” role

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRdisplay#36]
hi @takluyver, i was asked during the submission process by kurt how [this](https://github.com/IRkernel/IRdisplay/blob/master/LICENSE#L2) and [that](https://github.com/IRkernel/IRdisplay/blob/master/DESCRIPTION#L7-L8) fits together.

probably you should be “cre”?

see also IRkernel/IRkernel#322

**Comment by takluyver** [comment]
cre = creator?

Copyright holder should probably be something like 'IRkernel contributors', or 'Thomas Kluyver and contributors', since we don't ask people to assign us copyright. Shouldn't the LICENSE file also contain, you know, the license? E.g. [this](https://github.com/django/django/blob/master/LICENSE) is more what I expect a LICENSE file to look like.

As for the 'Authors' field in the description, I'm happy for you to arrange the credits in whatever way you think makes sense. I'd appreciate it if my name is in there, as sooner or later I'll have to persuade people to give me grants/jobs, and this is useful to show a bit of diversity in my open source work.

**Comment by flying-sheep** [comment]
OK, so IRkernel contributors and you’re the creator.

that’s both the most objective way to phrase it i think.

**Comment by jankatins** [comment]
I thought cre also be the uploader?

**Comment by flying-sheep** [comment]
you’re right, it says that:

`"cre" (Creator) Use for the package maintainer.`

i’ll wait for clarification.

**Comment by takluyver** [comment]
You're the most active, and you're the one dealing with CRAN, so if that's the meaning, feel free to make yourself 'cre'. :-)

**Comment by flying-sheep** [comment]
OK, cool. i’ve asked anyway, let’s see what kurt says

**Comment by flying-sheep** [comment]
fixed in https://github.com/IRkernel/IRdisplay/compare/9a3418d4ed17c487f074a201dd23c5785b9f606f...9c40b51707e5bd9870a8fe84ad190ecd6bc10bf6

**Comment by flying-sheep** [comment]
for the record: there need to be names in the LICENSE file, and all mentioned names need to have the “cph” role.

i suggest simply using GPL for future R projects
