### ISSUE TITLE
Display HTML output 

### ISSUE THREAD

**Issue by epifanio** [IRkernel/IRdisplay#37]
Hi, I just opened an issue on IRkernel, https://github.com/IRkernel/IRkernel/issues/392 but I realized that perhaps it is related to IRdisplay and not the kernel itself. should I close the issue and move it here instead?

**Comment by flying-sheep** [comment]
haha, thanks for considering it, people rarely do that.

but in this case, we are already able to display htmlwidgets via [repr_html.htmlwidget](https://irkernel.github.io/docs/repr/0.9/repr_-times-.htmlwidget.html).

your thing not being displayed is caused by packages tending to _not_ return something classed “htmlwidget”, but instead defining `print.theirclass <- function(o) print(as.htmlwidget(o))`.
